### ISSUE TITLE
Enhance current README

### ISSUE THREAD

**Issue by mkrcah** [slovensko-digital/harvester.ecosystem#19]
In order to simplify onboarding of new contributors, we should add the following information to README:
- how to start the application
- minimal description on what the application does (which sources are supported, what is the destination of the scraped data, etc)
- what dependencies does the application expect (e.g. a Postgres database)

**Comment by mkrcah** [comment]
Also, the current version supports two data sources: ITMS and UPVS/eDesk. However, [ecosystem.slovensko.digital](https://ekosystem.slovensko.digital) supports 8 data sources, including ITMS source, but excluding the UPVS/eDesk source. 

- How are other datasources supported by ecosystem downloaded? Where is the source code for them?

**Comment by jsuchal** [comment]
@mkrcah I am all in for better onboarding. Since this is a standard rails app, it's pretty straightforward for anyone doing Ruby/Rails development. 

Since I am biased and have deep down knowledge on how this works internally, i can't make judgments on what is problematic. Feel free to give suggestions, on where you got stuck. You seem not to be a ruby dev, so your mileage might vary. 

As for the data sources - thats a fair point. The other sources have not been opensourced yet. 

Upvs is used internally mostly for www.govbox.sk but it is documented at https://ekosystem.slovensko.digital/otvorene-data#upvs there is no api yet.

**Comment by mkrcah** [comment]
Thanks for the clear explanation.
 
- Indeed, I'm coming from a Python/Scala/Clojure, so the Ruby/Rails world is not straightforward. 
- Regarding getting the app running, I'm almost there - let's continue in PR #20 
- I'll also update the README with the data source overview, if that's ok
